"""Initial migration

Revision ID: dd4f97c8bdbd
Revises: 
Create Date: 2025-06-06 11:43:04.151334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4f97c8bdbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stars_earned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stars_earned')
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###
